# This is a basic workflow to help you get started with Actions

name: Setup

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Safety clause
    if: github.event.repository.name != 'IoTSense-Mlops-Template'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set RepoName as Experiment for mlflow
        run: sed -i '19s/IoTSense-Mlops-Template/${{ github.event.repository.name }}/g' $GITHUB_WORKSPACE/Untitled.ipynb

      - name: Commit changes
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "commit_made=false" >> $GITHUB_OUTPUT
          else
            git commit -m "Set variable in file"
            echo "commit_made=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Push changes
        if: steps.commit.outputs.commit_made == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
